# Generated by Django 3.2.2 on 2021-05-09 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('category', models.CharField(choices=[('1', 'Single'), ('2', 'Couple'), ('3', 'Widower'), ('4', 'Divorced')], max_length=30, null=True)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Transgenders'), ('4', 'Not To Say')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
