# Generated by Django 3.2.2 on 2021-05-09 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_remove_bio_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oser', to=settings.AUTH_USER_MODEL),
        ),
    ]
