# Generated by Django 3.2.2 on 2021-05-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0005_alter_bio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
