# Generated by Django 3.2.2 on 2021-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0006_bio_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='patner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
