# Generated by Django 3.2.2 on 2021-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0009_auto_20210511_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Rejected')], default=1, max_length=50),
        ),
    ]
