# Generated by Django 3.2.2 on 2021-05-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0012_bio_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='category',
            field=models.CharField(choices=[('1', 'Single'), ('2', 'Couple')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=50, null=True),
        ),
    ]
