# Generated by Django 3.2.2 on 2021-05-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['date']},
        ),
    ]
