# Generated by Django 3.2.2 on 2021-05-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[(1, 'Public'), (2, 'Friends'), (3, 'Only Me')], default=1, max_length=20),
        ),
    ]
