# Generated by Django 3.2.2 on 2021-05-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[(1, 'Public'), (2, 'Friends'), (3, 'Private')], default=1, max_length=20),
        ),
    ]
