# Generated by Django 3.2.2 on 2021-05-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_post_privacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['date'], 'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[(1, 'Public'), (2, 'Friends'), (3, 'Private')], default='Public', max_length=20),
        ),
    ]
