# Generated by Django 3.2.2 on 2021-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20210509_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Friends'), ('3', 'Private')], default='1', max_length=20),
        ),
    ]
