# Generated by Django 3.2.2 on 2021-05-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[('1', 'Like'), ('2', 'Comment'), ('3', 'follow'), ('4', 'Friend')]),
        ),
    ]
