# Generated by Django 3.2.2 on 2021-05-11 05:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('u1', 'u2')},
        ),
    ]
