# Generated by Django 3.2.2 on 2021-05-11 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0010_alter_friend_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='u1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to=settings.AUTH_USER_MODEL, verbose_name='From User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='u2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to=settings.AUTH_USER_MODEL, verbose_name='To User'),
        ),
    ]
