# Generated by Django 3.2.2 on 2021-05-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='evJqYnumnwwAttra4ikzBB', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
