# Generated by Django 3.2.2 on 2021-05-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('1', 'Like'), ('2', 'Comment'), ('3', 'follow'), ('4', 'Friend')], max_length=50),
        ),
    ]
